config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :blogs
  root 'blogs#index'
  get '/mypage', to: 'users#show', as: 'mypage'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      can :manage, Blog
      if user.admin?
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :histories, dependent: :destroy
    has_many :viewed_by_users, through: :histories, source: :user
    has_one_attached :image

    validates :title, :content, :user, presence: true
  
    def self.ransackable_attributes(auth_object = nil)
      %w(title content ingredients calories)
      
    end
    def self.ransackable_associations(auth_object = nil)
      []
    end
  end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :histories
  has_many :viewed_blogs, through: :histories, source: :blog

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  # before_action :authorize_user!, only: [:edit, :update, :destroy]
  after_action :track_history, only: [:show]
  before_action :correct_user!, only: [:edit, :update, :destroy]

  # GET /blogs or /blogs.json
  def index
    if user_signed_in?
      @q = Blog.ransack(params[:q])
      @blogs = @q.result(distinct: true)
    else
      @user = User.new
    end
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "Blog was successfully updated."
    else
      render :edit, status: :unprocessable_entity  
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def track_history
    return unless user_signed_in?
    current_user.histories.create(blog: @blog)
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :ingredients, :calories, :user_id)
  end

  # def authorize_user!
  #   unless current_user.admin?
  #     flash[:alert] = "管理者以外は編集や削除できません。"
  #     redirect_to root_path
  #   end
  # end

  def correct_user!
    unless @blog.user == current_user || current_user.admin?
      flash[:alert] = "自分の投稿しか編集・削除できません。"
      redirect_to root_path
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @viewed_blogs = @user.viewed_blogs
    @recipes = current_user.blogs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

    <div class="field">
    <%= form.label :ingredients, "材料" %>
    <%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :calories, "カロリー" %>
    <%= form.number_field :calories %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, accept: 'image/*', multiple: false %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% if user_signed_in? %>
  <%= search_form_for @q, url: blogs_path, method: :get do |f| %>
    <div class="field">
      <%= f.label :title_or_content_cont, "キーワード検索" %>
      <%= f.text_field :title_or_content_cont %>
    </div>
    <div class="actions">
      <%= f.submit "検索" %>
    </div>
  <% end %>

  <% @blogs.each do |blog| %>
    <div class="blog-entry">
      <h2><%= blog.title %></h2>
      <div class="blog-content">
        <p><%= blog.content %></p>
        <% if blog.image.attached? %>
          <div class="blog-image">
            <%= image_tag blog.image.variant(resize_to_limit: [300, 300]) %>
          </div>
        <% end %>
      </div>
      <div class="blog-details">
        <p><strong>材料:</strong> <%= blog.ingredients %></p>
        <p><strong>カロリー:</strong> <%= blog.calories %> kcal</p>
      </div>
      <div class="blog-actions">
        <%= link_to '詳細', blog %>
        <% if current_user.admin? %>
          <%= link_to '編集', edit_blog_path(blog) %>
          
          <%= link_to '削除', blog_path(blog), method: :delete, data: { confirm: '本当に削除しますか?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
  <br>
  <%= link_to 'レシピ投稿', new_blog_path %>
<% else %>
  <%= form_with(model: @user, url: user_session_path, local: true) do |form| %>
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password, autocomplete: "current-password" %>
    </div>

    <div class="field">
      <%= form.check_box :remember_me %>
      <%= form.label :remember_me %>
    </div>

    <div class="actions">
      <%= form.submit "Log in" %>
    </div>
  <% end %>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<h2>
  <strong>料理名:</strong>
  <%= @blog.title %>
</h2>

<div class="blog-details">
  <% if @blog.image.attached? %>
    <div class="blog-image">
      <%= image_tag @blog.image.variant(resize_to_limit: [350, 350]) %>
    </div>
  <% end %>

  <div class="blog-content">
    <div class="blog-box">
      <p>
        <strong>材料:</strong>
        <%= @blog.ingredients %>
      </p>

      <p>
        <strong>レシピ:</strong>
        <% @blog.content.split('。').each do |sentence| %>
          <p><%= sentence %>。
        <% end %>
      </p>

      <p>
        <strong>カロリー:</strong>
        <%= @blog.calories %> kcal
      </p>
    </div>
  </div>
</div>

<%= link_to '戻る', blogs_path %>

<% if current_user == @blog.user %>
  <%= link_to "編集", edit_blog_path(@blog) %> |
  <%= link_to "削除", @blog, method: :delete, data: { confirm: "本当に削除しますか？" } %>
<% end %>


<style>
  .blog-details {
    display: flex;
    align-items: flex-start;
  }

  .blog-image {
    flex: 1;
    margin-right: 20px;
  }

  .blog-content {
    flex: 2;
  }

  .blog-box {
    border: 2px solid #45a049;
    border-radius: 10px;
    padding: 20px;
    background-color: #ecf0f1;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }

  .blog-box p {
    margin: 10px 0;
  }

  .blog-box strong {
    color: #45a049;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>recipe app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">


  </head>

  <body>
    <header>
      <div class="container">
        <h1>Recipe App</h1>
        <nav>
          <% if user_signed_in? %>
            <%= link_to "レシピ一覧", blogs_path %>
            <%= link_to 'マイページ', mypage_path %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "新規登録", new_user_registration_path %>
            <%= link_to "ログイン", user_session_path %>
          <% end %>
        </nav>
      </div>
    </header>

    <main>
      <% unless user_signed_in? %>
        <section class="service-overview">
          <div class="container">
            <h2>サービス概要</h2>
            <p>何を作るか迷う料理、、あなたの料理のレパートリーを広げるため私たちがレシピを提案します。</p>
            <p>レシピを検索し、お気に入りの料理を見つけて、作り方を学びましょう。<strong>Recipe App</strong>で料理を楽しむ毎日を始めましょう！</p>
          </div>
        </section>
      <% end %>

      <%= yield %>
      
    </main>

    <footer>
      <div class="container">
        <p>&copy; 2024 Recipe App. All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<h1>マイページ</h1>

<h2>過去に見たレシピ</h2>
<ul>
  <% @viewed_blogs.each do |blog| %>
    <li><%= link_to blog.title, blog_path(blog) %></li>
  <% end %>
</ul>

<h2>自分の作成したレシピ</h2>
<ul>
  <% @user.blogs.each do |blog| %>
    <li>
      <h3><%= blog.title %></h3>
      <p><%= blog.content %></p>
      <%= link_to '編集', edit_blog_path(blog) %> |
      <%= link_to '削除', blog_path(blog), method: :delete, data: { confirm: '本当に削除しますか?' } %>
    </li>
  <% end %>
</ul>